### ISSUE TITLE
Publishing Proposal

### ISSUE THREAD

**Issue by aripiprazole** [Open-Pix/java-sdk#27]
This is a proposal for publishing the library onto the Maven Central repository! There are some resources for doing that:

- https://kotlinlang.org/docs/multiplatform-publish-lib.html
- https://mrcurious.medium.com/publishing-your-android-kotlin-library-to-maven-central-in-2021-df263a4f2cbc

And we will need the following pipeline:

- [x] Have a domain
- [x] Open ticket on https://issues.sonatype.org/ and do what's requested
- [x] Adapt the project to publish the library, like configuring the username and the private key
  - [x] Pull from the environment whats needed to a maven publication
        The code for helping here, can be: [andesite's buildscript](https://github.com/andesite-io/andesite/blob/main/build.gradle.kts)
- [x] Configure the CI to publish automatically whenever the repo creates a new release
  - [x] Setup private key on github actions

**Comment by daniloab** [comment]
- [ ] add a tutorial of how to open an issue on jira

**Comment by aripiprazole** [comment]
To register this Group Id you must prove ownership of the domain openpix.com. Please complete the following steps to continue:

    Add a DNS TXT record to your domain with the text: [OSSRH-93956](https://issues.sonatype.org/browse/OSSRH-93956). Please read https://central.sonatype.org/faq/how-to-set-txt-record/

More info: https://central.sonatype.org/publish/

If you do not own this domain, you may also choose a different Group Id that reflects your project hosting. io.github.open-pix would be valid based on your Project URL.
To continue the registration process, please follow these steps:

    Create a temporary, public repository called https://github.com/open-pix/OSSRH-93956 to verify github account ownership.
    Edit this ticket, update the Group ID field with the new GroupId, and set Status to Open.

More info: https://central.sonatype.org/publish/requirements/coordinates/

**Comment by sibelius** [comment]
<img width="1144" alt="image" src="https://github.com/Open-Pix/java-sdk/assets/2005841/ee086ea1-6395-42ff-9a7e-de57b8bdbbdb">

**Comment by aripiprazole** [comment]
[0.0.10](https://github.com/Open-Pix/java-sdk/actions/runs/6006705373/job/16291721934)
