### ISSUE TITLE
add webhook validation method

### ISSUE THREAD

**Issue by criskell** [Open-Pix/java-sdk#40]
- [ ] Add an method on `Webhooks` resource for checking if an given webhook signature is valid, returning `true` or `false`.
- [ ] Add docs for this method on https://github.com/Open-Pix/openpix-developers.

Useful resources:
- https://developers.openpix.com.br/docs/sdk/php/sdk-php-resources#validar-um-webhook
- https://developers.openpix.com.br/docs/webhook/webhook-signature-validation

Examples:
- https://github.com/Open-Pix/php-sdk/pull/34
- https://github.com/Open-Pix/ruby-sdk/pull/19

**Comment by aripiprazole** [comment]
https://github.com/Open-Pix/openpix-developers/pull/588
